nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'apiKeyAuth'] # important!!! apiKeyAuth and not api_key_auth in apache server because of the underscore
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
